DEVICE: cuda:0   # "cuda" for GPU  or "cpu"
IMAGE_SIZE: 640
BATCH_SIZE: 16
EPOCHS: 1000
LEARNING_RATE_0: 0.01
LEARNING_RATE_F: 0.01
AUGMENTATION: False  # Enable or disable data augmentation
AUGMENTATION_HYPERPARAMS:
  patience: 30
  momentum: 0.95
  weight_decay: 0.0001
  warmup_epochs: 10
  warmup_momentum: 0.5
  warmup_bias_lr: 0.1
  optimizer: SGD
  hsv_h: 0.015
  hsv_s: 0.8
  hsv_v: 0.1  
  degrees: 0
  translate: 0.1
  scale: 0.7
  mosaic: 0
  mixup: 1
  flipud: 0
  fliplr: 0.5
  shear: 25 
  perspective: 0.001