artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1297WLL9_ULuZtsnYN_SOseNEiEbv15Dd/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  dataset_name: Workplace-Safety-Dataset
  data_yaml_file: artifacts/data_ingestion/Workplace-Safety-Dataset/data.yaml




model_preparation_and_training:
  root_dir: artifacts/model_preparation_and_training
  data_yaml_file: artifacts/data_ingestion/Workplace-Safety-Dataset/data.yaml
  yolo_model: yolov8n.pt



evaluation:
  root_dir: artifacts/evaluation
  best_model: artifacts/model_preparation_and_training/yolov8n_training/weights/best.pt
  data_yaml_file: artifacts/data_ingestion/Workplace-Safety-Dataset/data.yaml